### ISSUE TITLE
how to install on ubuntu18.04

### ISSUE THREAD

**Issue by airforce011** [noxdafox/clipspy#10]
I followed the instruction on https://pypi.org/project/clipspy/, but could net set it up.
I have compiled the clips core and cp *.h to /usr/local/include/clips and cp *.a to /usr/lib/clips
but it does not work. "Failed building wheel for clipspy"
waiting for help

**Comment by noxdafox** [comment]
Hello,

you can install the [library](https://packages.debian.org/sid/libclips) and the [headers](https://packages.debian.org/sid/libclips-dev) from debian via `dpkg` which should make things simpler.

If you want to manually compile CLIPS you need to specify the headers and library location via the `CFLAGS` and `LDFLAGS` environment variable as per the example in the README.

**Comment by airforce011** [comment]
I have got it.
download the 2 deb packages and $sudo dpkg -i xxx.deb 
and then $pip install clipspy
Thanks a lot!
