### ISSUE TITLE
All activated rules fired simultaneiously

### ISSUE THREAD

**Issue by srajan3012** [noxdafox/clipspy#11]
if fact1, fact2, fact3 are asserted at the same time, then while using [PyCLIPS](http://pyclips.sourceforge.net/web/) depending on the order of declaration of rules in my .clp file, rule1 was fired.(because it precedes rule2)
```
(defrule rule1
  (fact 1)
  (fact 2)
=> printout t"rule1")

(defrule rule2
  (fact 1)
  (fact 3)
=> printout t"rule2")
```
but `clipspy` fires both the rules at the same time. This messes up the expert system as there are two ouputs on the screen.
I understand I'll have to (declare (salience __)) in each rule to prioritze rules. This is an extra burden as when my rules increase in number, its hard to keep track of salience numbers. 
Is there a way to prioritize rules based on their order in the .clp file.

**Comment by noxdafox** [comment]
This is not an issue of clipspy itself but rather the way RETE-based expert systems operate.

When facts are asserted within the engine, they will eventually satisfy the conditions for your rules to activate. As soon as a rule LHS is satisfied, the RHS gets placed within the agenda. The agenda can be represented as a stack of instructions to execute. 

It is important to note that in CLIPS, the facts are evaluated against the rules LHS once asserted whereas the actions in the agenda are executed when `(run)` (in clipspy `environment.run()`) is called.

It is a responsibility of the rules developer to instruct the engine on how to sort the actions once they are placed in the agenda. CLIPS provides two mechanisms: the salience and the conflict resolution strategy.
The salience provides fine-grained control over the rules firing order allowing the user to hardcode their priority. The conflict resolution strategy instead, is the algorithm responsible to sort the agenda when rules have the same salience/priority.

You can find more information regarding the agenda, the salience and the conflict resolution strategy in the CLIPS [Basic Programming Guide](http://clipsrules.sourceforge.net/documentation/v630/bpg.pdf).

**Comment by srajan3012** [comment]
why both rules are fired here instead of one rule if conflict resolution strategy is used in absence of salience

**Comment by noxdafox** [comment]
Please use GitHub for issues related to clipspy and not generic knowledge questions. For these matters, the CLIPS [discussion](https://sourceforge.net/p/clipsrules/discussion/) forum and [stackoverflow](https://stackoverflow.com/questions/tagged/clips) are much better suited.

If you assert all 3 facts, then you activate both rules and both will fire. You can easily test this on the CLIPS console.

```
$ clips
CLIPS (6.30 3/17/15)
CLIPS> (defrule rule1
  (fact 1)
  (fact 2)
=> (printout t "rule1"))
CLIPS> (defrule rule2
  (fact 1)
  (fact 3)
=> (printout t "rule2"))
CLIPS> (assert (fact 1))
<Fact-1>
CLIPS> (assert (fact 2))
<Fact-2>
CLIPS> (assert (fact 3))
<Fact-3>
CLIPS> (agenda)
0      rule2: f-1,f-3
0      rule1: f-1,f-2
For a total of 2 activations.
CLIPS> (run)
rule2rule1
```

Note how when printing the agenda content via `(agenda)`, both rules are placed within and note how they are sorted as a stack (LIFO). This because the default conflict resolution strategy is `depth`. Changing it to `breadth` will provide opposite sorting.

```
$ clips
CLIPS (6.30 3/17/15)
CLIPS> (set-strategy breadth)
depth
CLIPS> (defrule rule1
  (fact 1)
  (fact 2)
=> (printout t "rule1"))
CLIPS> (defrule rule2
  (fact 1)
  (fact 3)
=> (printout t "rule2"))
CLIPS> (assert (fact 1))
<Fact-1>
CLIPS> (assert (fact 2))
<Fact-2>
CLIPS> (assert (fact 3))
<Fact-3>
CLIPS> (agenda)
0      rule1: f-1,f-2
0      rule2: f-1,f-3
For a total of 2 activations.
CLIPS> (run)
rule1rule2
```
