### ISSUE TITLE
How to retract a slot value of a template

### ISSUE THREAD

**Issue by srajan3012** [noxdafox/clipspy#13]
```
;;---KB.clp---;;
(deftemplate fact_template
        (slot slot_1
                (type SYMBOL))
        (slot slot_2
                (type SYMBOL))
)
(assert (fact 1))
(assert (fact_template (slot_1 v1) (slot_2 v2)))
(defrule rule1
  (fact 1)
  =>
  ?p <- (fact_template (slot_1 ?s1)
  ?q <- (fact_template (slot_2 ?s2)
  (py_retract ?p ?q))
```

```
# run.py
import clips
clips_env = clips.Environment()
clips_env.load("KB.clp")

def py_retract(p, q):
    env.build('retract '+str(p))

clips_env.define_function(py_retract)
clips_env.run()
```
This does not works as both p and q are not fact-identifier but come as entire fact-template.
How to change only one slot of the template keeping other intact.

**Comment by noxdafox** [comment]
As I already mention in issue #11, GitHub is not the right place for general questions. For that, please use the official CLIPS [forum](https://sourceforge.net/p/clipsrules/discussion/) and [stackoverflow](https://stackoverflow.com/questions/tagged/clips). Please limit the usage of GitHub issues for bugs or feature requests which are strictly related to the `clipspy` Python bindings.

This said, before deep diving into integrating CLIPS into any platform I'd recommend you to first get familiar with the CLIPS language itself. You can refer to its [Basic Programming Guide](http://clipsrules.sourceforge.net/documentation/v630/bpg.pdf) and to help yourself you can either use the CLIPS native console or its [Jupyter counterpart](https://pypi.org/project/iCLIPS/).

Once you are familiar with the CLIPS language and its quirks, you can refer to the [Advanced Programming Guide](http://clipsrules.sourceforge.net/documentation/v630/apg.pdf) to better understand how to integrate it into your software. You will then realize that `clipspy` is just a thin wrapper of CLIPS C programming interface. You can also refer to `clipspy` documentation at the following [link](https://clipspy.readthedocs.io).

The code you are posting is incorrect. `(fact_template (slot_1 ?s1)` is broken as the number of parenthesis do not match. `(fact_template (slot_1 ?s1))` is not going to do what you think. It's going to call a function `fact_template` which does not exists and therefore the rule execution will stop.

```
$ clips
         CLIPS (6.30 3/17/15)
CLIPS> (deftemplate foo)
CLIPS> (foo 1)

[EXPRNPSR3] Missing function declaration for foo.
```
