### ISSUE TITLE
Supporting mypy type checking

### ISSUE THREAD

**Issue by gitttt** [noxdafox/clipspy#14]
Would be great to have mypy type checking support.

We could add this for one function after the other. It would not interrupt the regular functioning.

**Comment by noxdafox** [comment]
This is something I was investigating already a bit in the past. Issue is type hints are not supported in Python 2 and maintaining two different code bases would be quite a difficult task.

Only solution would be to drop Python 2 support which I intend to do anyways as its support from the community ends next year.

This is indeed what's happening in the bindings for the version 6.40. You can check its [development branch](https://github.com/noxdafox/clipspy/tree/6.40). The code base looks promising and all tests are already passing. I still need to update the documentation and have a general revision. I will release clipspy 6.40 once its counterpart in C is declared stable by the author.

Right now the goal is to simplify the building process (I already added a Makefile) especially on Linux and I am playing with the idea of supporting different CLIPS distribution like my [customisations](https://github.com/noxdafox/clips/tree/regex) and [FuzzyCLIPS](https://github.com/garydriley/FuzzyCLIPS631) as the APIs should be compatible.

**Comment by noxdafox** [comment]
CLIPSPy 6.40 is ready. I will release it once CLIPS 6.40 is released officially.

You might want to give it a try as the new APIs solve several issues you have been facing with the 6.30 ones.

The new APIs allow to programmatically create instances at once, modify already made ones (same thing for facts) and other things such as calling CLIPS functions without the need to use `eval`.

```python
defclass = """
(defclass MyClass (is-a USER)
  (slot One)
  (slot Two))
"""

env.build(defclass)

defclass = env.find_class("MyClass")
instance = defclass.make_instance("MyInstance", One=1, Two=2)
fact = env.assert_string('(foo bar baz)')
instance.modify_slots(One=fact)

multifield = env.call('create$', 1, 2.0, "three", clips.Symbol("four"), clips.InstanceName("five"))
```

**Comment by noxdafox** [comment]
`clipspy` `1.0.0` now supports type hints.
