### ISSUE TITLE
How to link two clips objects

### ISSUE THREAD

**Issue by gitttt** [noxdafox/clipspy#15]
I have created a class instance named `UniversalSample.exe`.

Now I have the following string:

`'(make-instance my_function of clips_NETWORK_FUNCTION (binary [UniversalSample.exe])(start_address 4278884)(function_name "blah"))'`

This creates a new class instance:

`clips_env.eval(make_instance_string)`

Then I obtain the newly created class instance via:

`instance_just_created = clips_env.find_instance(clips_instance_name)`

However, 

`type(instance_just_created["binary"])`

returns

<class 'str'>`

but not (as I expected)

`<class 'clips.classes.Instance'>`

How can I create a class instance that has a property pointing to another class instance that I know the name of?

**Comment by gitttt** [comment]
Here is a full example:

import clips


```
env = clips.Environment()


binary_class_string = """
(defclass clips_BINARY (is-a USER)
  (slot path))
"""
env.build(binary_class_string)

network_function_class_string = """
(defclass clips_NETWORK_FUNCTION (is-a USER)
  (slot binary)
  (slot start_address))
"""
env.build(network_function_class_string)


make_binary_instance_string = '(make-instance UniversalSample.exe of clips_BINARY (path /path/to/binary))'
env.eval(make_binary_instance_string)
instance_just_created = env.find_instance("UniversalSample.exe")
print(instance_just_created)

make_network_function_instance_string = '(make-instance my_func of clips_NETWORK_FUNCTION (binary [UniversalSample.exe])(start_address 4278884))'
env.eval(make_network_function_instance_string)
instance_just_created = env.find_instance("my_func")
print(instance_just_created)
print(type(instance_just_created["binary"]))
```

**Comment by gitttt** [comment]
If I always have to go over the name, e.g. do a

```
instance_just_created = env.find_instance("my_func")
linked_instance = env.find_instance(instance_just_created["binary"])
```

how can I know if a slot contains a string or an instance name?

**Comment by noxdafox** [comment]
Your example behaves correctly as you are passing to the `binary` slot the instance name and not its address. To retrieve the address of an instance, you can use CLIPS `instance-address` function.

```python
In [3]: env.eval('(make-instance my_func of clips_NETWORK_FUNCTION (binary (instance-address [UniversalSample.exe]))(start_address 4278884))')
Out[3]: 'my_func'

In [4]: instance = env.find_instance('my_func')

In [5]: instance['binary']
Out[5]: Instance: [UniversalSample.exe] of clips_BINARY (path /path/to/binary)
```
