### ISSUE TITLE
Installing on Mac OSX

### ISSUE THREAD

**Issue by RubberDucky32** [noxdafox/clipspy#18]
Hey there, 

I've looked at other threads addressing installation issues and didn't find an answer, probably through my own incompetence, but please stay with me..

I'm trying to install clipspy on my Mac, running os 10.14, with Python 3.7.2.  Attempted running "pip install clipspy" and got this error: 

` build/temp.macosx-10.14-x86_64-3.7/_clips.c:523:10: fatal error: 'clips.h' file not found
    #include <clips.h>
             ^~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
`

I went to [https://pypi.org/project/clipspy/#files](url) but could not find a wheel that works.

Downloaded the .tar.gz at the above link and tried: `./pip3 install ~/Downloads/clipspy-0.3.2.tar.gz ` which returned the same error as above.

I have the clips source code, I'm just not sure where to place it to circumvent that error.  Here is the full terminal error.

`$ ./pip3 install ~/Downloads/clipspy-0.3.2.tar.gz 
Processing /Users/paulvajda/Downloads/clipspy-0.3.2.tar.gz
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.7/site-packages (from clipspy==0.3.2) (1.12.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi>=1.0.0->clipspy==0.3.2) (2.19)
Building wheels for collected packages: clipspy
  Building wheel for clipspy (setup.py) ... error
  Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/fg/wcnyz_gn7ndb5yf8b26b4dw80000gn/T/pip-req-build-_yvyr_53/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/fg/wcnyz_gn7ndb5yf8b26b4dw80000gn/T/pip-wheel-ystgkg_s --python-tag cp37:
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/functions.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/facts.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/agenda.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/error.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/clips_build.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/common.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/environment.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/modules.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/classes.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/router.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  copying clips/data.py -> build/lib.macosx-10.14-x86_64-3.7/clips
  running build_ext
  generating cffi module 'build/temp.macosx-10.14-x86_64-3.7/_clips.c'
  creating build/temp.macosx-10.14-x86_64-3.7
  building '_clips' extension
  creating build/temp.macosx-10.14-x86_64-3.7/build
  creating build/temp.macosx-10.14-x86_64-3.7/build/temp.macosx-10.14-x86_64-3.7
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c build/temp.macosx-10.14-x86_64-3.7/_clips.c -o build/temp.macosx-10.14-x86_64-3.7/build/temp.macosx-10.14-x86_64-3.7/_clips.o
  build/temp.macosx-10.14-x86_64-3.7/_clips.c:523:10: fatal error: 'clips.h' file not found
  #include <clips.h>
           ^~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for clipspy
  Running setup.py clean for clipspy
Failed to build clipspy
Installing collected packages: clipspy
  Running setup.py install for clipspy ... error
    Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/fg/wcnyz_gn7ndb5yf8b26b4dw80000gn/T/pip-req-build-_yvyr_53/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/fg/wcnyz_gn7ndb5yf8b26b4dw80000gn/T/pip-record-mgouyx3m/install-record.txt --single-version-externally-managed --compile:
    fatal: not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/functions.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/facts.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/agenda.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/error.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/clips_build.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/common.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/environment.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/modules.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/classes.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/router.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    copying clips/data.py -> build/lib.macosx-10.14-x86_64-3.7/clips
    running build_ext
    generating cffi module 'build/temp.macosx-10.14-x86_64-3.7/_clips.c'
    creating build/temp.macosx-10.14-x86_64-3.7
    building '_clips' extension
    creating build/temp.macosx-10.14-x86_64-3.7/build
    creating build/temp.macosx-10.14-x86_64-3.7/build/temp.macosx-10.14-x86_64-3.7
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c build/temp.macosx-10.14-x86_64-3.7/_clips.c -o build/temp.macosx-10.14-x86_64-3.7/build/temp.macosx-10.14-x86_64-3.7/_clips.o
    build/temp.macosx-10.14-x86_64-3.7/_clips.c:523:10: fatal error: 'clips.h' file not found
    #include <clips.h>
             ^~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/fg/wcnyz_gn7ndb5yf8b26b4dw80000gn/T/pip-req-build-_yvyr_53/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/fg/wcnyz_gn7ndb5yf8b26b4dw80000gn/T/pip-record-mgouyx3m/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/fg/wcnyz_gn7ndb5yf8b26b4dw80000gn/T/pip-req-build-_yvyr_53/
`

Help is much appreciated,

Cheers

**Comment by noxdafox** [comment]
Hello,

`clipspy` is a `cffi` wrapper of CLIPS APIs. In order to install it via `pip`, you need to have the CLIPS library and its headers installed within the system. The `setup.py` will try to find them if they are located in their default location (which in MAC OS might differ from other Unix OSes). 

You have two options: 

1. You install CLIPS into your system and then try again with `pip install` passing the paths of the library and its headers via `LDFLAGS` and `CFLAGS`. This might still give you problems if the library has not been compiled as a shared one.
2. You retrieve the last [release](https://github.com/noxdafox/clipspy/releases/tag/0.3.2) unpack it and follow the [Building from Sources](https://github.com/noxdafox/clipspy#building-from-sources) instructions.

**Comment by RubberDucky32** [comment]
Thank you for getting back to me on this.  I have not yet had the time to try out your suggestions, but will report back when I do.

**Comment by RubberDucky32** [comment]
Update:

I downloaded the last release and tried following the Building From Sources instructions.  I was getting issues so opened up the Makefile in emacs, and a little researched informed me that 'sed' is not supported on MacOSX, so a quick  `brew install gnu-sed`, followed by replacing `sed` with `gsed` did the trick.

That way, I've got the clips source downloaded and the `xxx.o` files created.

The next issue seems to be around the -G flag used in the ld command within the makefile...

`ld -G clips_source/*.o -o clips_source/libclips.so
ld: unknown option: -G`

But I can't seem to find any information online about what the `-G` flag does, so I can't find the macOSX equivalent/replacement.

Any insights?

**Comment by noxdafox** [comment]
You should be able to safely remove that parameter.

**Comment by RubberDucky32** [comment]
Removing `-G` throws..

`Undefined symbols for architecture x86_64:
  "__DefaultRuneLocale", referenced from:
      _CompleteCommand in commline.o
      _ReadNumber in iofun.o
      _GetToken in scanner.o
      _ScanSymbol in scanner.o
      _ScanNumber in scanner.o
      _UpcaseFunction in strngfun.o
      _LowcaseFunction in strngfun.o
      ...
  "___bzero", referenced from:
      _ParseDefclass in classpsr.o
      _AllocateEnvironmentData in envrnmnt.o
      _CreateEnvironmentDriver in envrnmnt.o
      _AddHashedFact in facthsh.o
      _RemoveHashedFact in facthsh.o
      _InitializeFactHashTable in facthsh.o
      _InitializeFacts in factmngr.o
      ...
  "___error", referenced from:
      _ScanNumber in scanner.o
  "___maskrune", referenced from:
      _CompleteCommand in commline.o
      _ReadNumber in iofun.o
      _GetToken in scanner.o
      _ScanSymbol in scanner.o
      _ScanNumber in scanner.o
      _UpcaseFunction in strngfun.o
      _LowcaseFunction in strngfun.o
      ...
  "___sprintf_chk", referenced from:
      _EnvJoinActivity in rulecom.o
  "___stack_chk_fail", referenced from:
      _AddActivation in agenda.o
      _PrintActivation in agenda.o
      _RemoveActivation in agenda.o
      _EnvGetActivationPPForm in agenda.o
      _GetFactOrInstanceArgument in argacces.o
      _EnvBload in bload.o
      _EnvBsave in bsave.o
      ...
  "___stack_chk_guard", referenced from:
      _AddActivation in agenda.o
      _PrintActivation in agenda.o
      _RemoveActivation in agenda.o
      _EnvGetActivationPPForm in agenda.o
      _GetFactOrInstanceArgument in argacces.o
      _EnvBload in bload.o
      _EnvBsave in bsave.o
      ...
  "___stdinp", referenced from:
      _CommandLoop in commline.o
      _CommandLoopBatchDriver in commline.o
      _GetcFile in filertr.o
      _UngetcFile in filertr.o
      _FindFptr in filertr.o
      _gengetchar in sysdep.o
      _genungetchar in sysdep.o
      ...
  "___stdoutp", referenced from:
      _FindFptr in filertr.o
  "___strcat_chk", referenced from:
      _genstrcat in sysdep.o
  "___strncat_chk", referenced from:
      _genstrncat in sysdep.o
  "___tolower", referenced from:
      _LowcaseFunction in strngfun.o
  "___toupper", referenced from:
      _UpcaseFunction in strngfun.o
      _TextLookupFetch in textpro.o
      _GetEntries in textpro.o
  "___vsprintf_chk", referenced from:
      _gensprintf in sysdep.o
  "_acos", referenced from:
      _AcosFunction in emathfun.o
      _AsecFunction in emathfun.o
  "_asin", referenced from:
      _AsinFunction in emathfun.o
      _AcscFunction in emathfun.o
  "_atan", referenced from:
      _AtanFunction in emathfun.o
      _AcotFunction in emathfun.o
  "_atof", referenced from:
      _ScanNumber in scanner.o
  "_atoi", referenced from:
      _CheckFunctionArgCount in argacces.o
      _CheckExpressionAgainstRestrictions in exprnpsr.o
      _GetMinimumArgs in extnfunc.o
      _GetMaximumArgs in extnfunc.o
      _AddImplicitMethods in immthpsr.o
  "_clearerr", referenced from:
      _GetcFile in filertr.o
  "_clock", referenced from:
      _gentime in sysdep.o
  "_cos", referenced from:
      _CosFunction in emathfun.o
      _TanFunction in emathfun.o
      _SecFunction in emathfun.o
      _CotFunction in emathfun.o
  "_cosh", referenced from:
      _CoshFunction in emathfun.o
      _SechFunction in emathfun.o
  "_exit", referenced from:
      _genexit in sysdep.o
  "_exp", referenced from:
      _ExpFunction in emathfun.o
  "_fclose", referenced from:
      _GenClose in sysdep.o
      _GenCloseBinary in sysdep.o
  "_fflush", referenced from:
      _CommandLoop in commline.o
      _CommandLoopBatchDriver in commline.o
      _genprintfile in sysdep.o
  "_fgets", referenced from:
      _TextLookupFetch in textpro.o
      _grab_string in textpro.o
  "_fopen", referenced from:
      _GenOpen in sysdep.o
      _GenOpenReadBinary in sysdep.o
  "_fprintf", referenced from:
      _ConstructsToCCommand in conscomp.o
      _PrintFunctionReference in conscomp.o
      _NewCFile in conscomp.o
      _PrintHashedExpressionReference in conscomp.o
      _ExpressionToCode in conscomp.o
      _DumpExpression in conscomp.o
      _OpenFileIfNeeded in conscomp.o
      ...
  "_fputc", referenced from:
      _ConstructsToCCommand in conscomp.o
      _NewCFile in conscomp.o
      _ExpressionToCode in conscomp.o
      _DumpExpression in conscomp.o
      _OpenFileIfNeeded in conscomp.o
      _ConstructHeaderToCode in conscomp.o
      _ConstructModuleToCode in conscomp.o
      ...
  "_fputs", referenced from:
      _EnvDribbleOff in filecom.o
      _ExitDribble in filecom.o
      _PutcDribbleBuffer in filecom.o
      _EnvPrintRouter in router.o
      _AtomicValuesToCode in symblcmp.o
      _genprintfile in sysdep.o
  "_fread", referenced from:
      _GenReadBinary in sysdep.o
  "_free", referenced from:
      _CreateEnvironmentDriver in envrnmnt.o
      _DestroyEnvironment in envrnmnt.o
      _genalloc in memalloc.o
      _EnvReleaseMem in memalloc.o
      _genfree in memalloc.o
      _genrealloc in memalloc.o
      _rm in memalloc.o
      ...
  "_fseek", referenced from:
      _GetSeekCurBinary in sysdep.o
      _GetSeekSetBinary in sysdep.o
      _FindTopicInEntries in textpro.o
      _GetEntries in textpro.o
  "_ftell", referenced from:
      _GenTellBinary in sysdep.o
      _TextLookupFetch in textpro.o
  "_fwrite", referenced from:
      _ConstructsToCCommand in conscomp.o
      _PrintFunctionReference in conscomp.o
      _PrintHashedExpressionReference in conscomp.o
      _ExpressionToCode in conscomp.o
      _DumpExpression in conscomp.o
      _CloseFileIfNeeded in conscomp.o
      _OpenFileIfNeeded in conscomp.o
      ...
  "_getc", referenced from:
      _LLGetcBatch in filecom.o
      _EnvBatchStar in filecom.o
      _GetcFile in filertr.o
      _EnvGetcRouter in router.o
      _gengetchar in sysdep.o
      _GenOpen in sysdep.o
      _TextLookupFetch in textpro.o
      ...
  "_log", referenced from:
      _AcoshFunction in emathfun.o
      _AsinhFunction in emathfun.o
      _AtanhFunction in emathfun.o
      _AsechFunction in emathfun.o
      _AcschFunction in emathfun.o
      _AcothFunction in emathfun.o
      _LogFunction in emathfun.o
      ...
  "_log10", referenced from:
      _Log10Function in emathfun.o
  "_longjmp", referenced from:
      _genexit in sysdep.o
  "_main", referenced from:
     implicit entry/start for main executable
  "_malloc", referenced from:
      _AllocateEnvironmentData in envrnmnt.o
      _CreateEnvironmentDriver in envrnmnt.o
      _AddEnvironmentCleanupFunction in envrnmnt.o
      _InitializeMemory in memalloc.o
      _genalloc in memalloc.o
  "_memcpy", referenced from:
      _AddClassLink in classfun.o
      _DeleteSubclassLink in classfun.o
      _DeleteSuperclassLink in classfun.o
      _SetupObjectSystem in classini.o
      _UpdateDefclassesScope in classini.o
      _ParseDefclass in classpsr.o
      _SetupDeffunctions in dffnxfun.o
      ...
  "_memmove", referenced from:
      _InsertInString in utility.o
  "_memset_pattern16", referenced from:
      _DefgenericsToCode in genrccmp.o
      _ObjectsToCode in objcmp.o
  "_pow", referenced from:
      _PowFunction in emathfun.o
  "_printf", referenced from:
      _AllocateEnvironmentData in envrnmnt.o
      _DestroyEnvironment in envrnmnt.o
  "_putc", referenced from:
      _PutCharFunction in iofun.o
  "_puts", referenced from:
      _CreateEnvironmentDriver in envrnmnt.o
      _DestroyEnvironment in envrnmnt.o
  "_rand", referenced from:
      _genrand in sysdep.o
  "_remove", referenced from:
      _genremove in sysdep.o
  "_rename", referenced from:
      _genrename in sysdep.o
  "_setlocale", referenced from:
      _IOFunctionDefinitions in iofun.o
      _FormatFunction in iofun.o
      _ReadNumber in iofun.o
  "_sin", referenced from:
      _SinFunction in emathfun.o
      _TanFunction in emathfun.o
      _CscFunction in emathfun.o
      _CotFunction in emathfun.o
  "_sinh", referenced from:
      _SinhFunction in emathfun.o
      _CschFunction in emathfun.o
  "_srand", referenced from:
      _genseed in sysdep.o
  "_sscanf", referenced from:
      _TextLookupFetch in textpro.o
  "_strcmp", referenced from:
      _SetSalienceEvaluationCommand in agenda.o
      _GetLogicalName in argacces.o
      _GetModuleName in argacces.o
      _EnvBload in bload.o
      _SetClassDefaultsModeCommand in classcom.o
      _SlotExistPCommand in classexm.o
      _ClassInfoFnxArgs in classinf.o
      ...
  "_strcpy", referenced from:
      _genstrcpy in sysdep.o
  "_strlen", referenced from:
      _EnvBload in bload.o
      _EnvBsave in bsave.o
      _EnvDescribeClass in classexm.o
      _AddSlotName in classfun.o
      _RemoveDefclass in classfun.o
      _DestroyDefclass in classfun.o
      _SetCommandString in commline.o
      ...
  "_strncmp", referenced from:
      _EnvBload in bload.o
      _ReplaceFactVariables in factqpsr.o
      _ReplaceInstanceVariables in insqypsr.o
      _IsParameterSlotReference in msgpsr.o
      _SlotReferenceVar in msgpsr.o
      _BindSlotReference in msgpsr.o
      _ReplaceMvPrognFieldVars in multifun.o
      ...
  "_strncpy", referenced from:
      _genstrncpy in sysdep.o
  "_strtod", referenced from:
      _ReadNumber in iofun.o
  "_strtoll", referenced from:
      _ReadNumber in iofun.o
      _ScanNumber in scanner.o
  "_tanh", referenced from:
      _TanhFunction in emathfun.o
      _CothFunction in emathfun.o
  "_ungetc", referenced from:
      _UngetcBatch in filecom.o
      _UngetcFile in filertr.o
      _EnvUngetcRouter in router.o
      _genungetchar in sysdep.o
      _GenOpen in sysdep.o
      _TextLookupFetch in textpro.o
ld: symbol(s) not found for inferred architecture x86_64
make: *** [clips] Error 1
`

I'll keep searching.

**Comment by RubberDucky32** [comment]
To install clipspy 0.3.2 on Mac OSX 10.14.4 Mojave, Python 3.7.2:

1. Start by downloading CLIPS 6.30: https://sourceforge.net/projects/clipsrules/files/CLIPS/6.30/ -> clips_core_source_630.tar.Z
1. In terminal, in your directory of choice: `mkdir clips-6.3.0`
1. `cd clips-6.3.0`
1. place the clips source file in `clips-6.3.0` and  `tar -xvzf clips_core_source_630.tar.Z`
1. `cd clips_core_source_630/core`
1. `make -f ../makefiles/makefile.lib`
1. Save the path you are currently in by creating an environment variable.  In terminal, type: `pwd`
1. `CLIPS_PATH=thepath` -> important to not surround the `=` with spaces!
1. Now download clipspy 0.3.2 source file: https://github.com/noxdafox/clipspy/archive/0.3.2.tar.gz
1. `tar -xvzf clipspy-0.3.2.tar.gz`
1. `cd clipspy-0.3.2`
1. `python setup.py build_ext --include-dirs $CLIPS_PATH --library-dirs $CLIPS_PATH install`
1. In the "test" directory, create a file called `__init__.py` and paste the attached at the bottom of this post
1. `python setup.py build_ext --include-dirs $CLIPS_PATH --library-dirs $CLIPS_PATH test`
1. Should run 38 tests successfully :-)

For `__init__.py`

~~~~
import sys

if __name__ == "__main__":
   if sys.version_info >= (2, 7):
       import os, unittest

       def load_tests(loader, standard_tests, pattern):
           if pattern is None:
               pattern = 'test*.py'
           this_dir = os.path.dirname(__file__)
           package_tests = loader.discover(start_dir=this_dir, pattern=pattern)
           standard_tests.addTests(package_tests)
           return standard_tests

       unittest.main()
   else:
       print >>sys.stderr, 'Unit test discovery requires Python 2.7 or later'
       try:
           from pkg_resources import require
           with_setuptools = require('setuptools')[0].parsed_version
           print >>sys.stderr, "Use: 'python setup.py test' instead"
       except ImportError:
           pass

**Comment by noxdafox** [comment]
Thanks for the info and sorry for the late reply. 

I am curious regarding your previous issues as the workflow you posted is pretty close to the documented one and the provided `Makefile` should already work. Did you have some issue with your environment?

Also to run the tests you don't technically need an `__init__.py` file in the `test` folder, the following command should work:

```bash
$ python -m unittest discover -p *_test.py -s test/
```

Reason why tests don't work out of the box is that I mistakenly named them `*_test.py` whereas `unittest` looks for the following pattern by default `test*.py`. I will later on rename all the files.

**Comment by noxdafox** [comment]
This should be now covered by #32. Kudos to @DArtagan!

**Comment by ramakrse** [comment]
I get the below error (partial - last elements) while installing using pip install clipspy.
build/temp.macosx-10.9-x86_64-cpython-312/_clips.c:570:10: fatal error: 'clips.h' file not found
      #include <clips.h>
               ^~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for clipspy
  Running setup.py clean for clipspy
Failed to build clipspy
ERROR: Could not build wheels for clipspy, which is required to install pyproject.toml-based projects
