### ISSUE TITLE
fatal error C1083: Cannot open include file: 'clips.h': No such file or directory

### ISSUE THREAD

**Issue by gitttt** [noxdafox/clipspy#2]
I am using Windows. How do I tell the installer where to find the `clips.h`?

I tried adapting the `setup.py` but it did not work.

Moreover, what code exactly should I download? This one:
https://sourceforge.net/projects/clipsrules/files/CLIPS/6.30/clips_core_source_630.zip/download
?

**Comment by gitttt** [comment]
I advanced:

- Moved the `makefile.win` file into the c:\tmp\clips_core_source_630\core directory. 
- Locate vcvarsall.bat in the Visual Studio directories and run from the Command Prompt application.
- Navigate to the core directory and enter the command `nmake -f makefile.win` which created an executable
- `lib.exe /OUT:clips.lib *.obj` 
   created a library, (what did the `-G` ld flag do? How do I do it with `lib.exe` or `link.exe`?
- `python setup.py build_ext --include-dirs c:\tmp\clips_core_source_630\core --library-dirs c:\tmp\clips_core_source_630\core`
- c:\tmp\clipspy>python setup.py build_ext --include-dirs c:\tmp\clips_core_source_630\core --library-dirs c:\tmp\clips_core_source_630\core
```
C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\dist.py:407: UserWarning: The version specified ('0.2.4-4-g714e8a2') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running build_ext
generating cffi module 'build\\temp.win-amd64-3.7\\Release\\_clips.c'
already up-to-date
building '_clips' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\tmp\clips_core_source_630\core -IC:\Python37\include -IC:\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /Tcbuild\temp.win-amd64-3.7\Release\_clips.c /Fobuild\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release\_clips.obj
_clips.c
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\tmp\clips_core_source_630\core /LIBPATH:C:\Python37\libs /LIBPATH:C:\Python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" clips.lib /EXPORT:PyInit__clips build\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release\_clips.obj /OUT:build\lib.win-amd64-3.7\clips\_clips.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release\_clips.cp37-win_amd64.lib
_clips.obj : warning LNK4197: export 'PyInit__clips' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release\_clips.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release\_clips.cp37-win_amd64.exp
_clips.obj : error LNK2001: unresolved external symbol EnvAddLong
_clips.obj : error LNK2001: unresolved external symbol EnvMakeInstance
_clips.obj : error LNK2001: unresolved external symbol EnvGetSalienceEvaluation
[...]
_clips.obj : error LNK2001: unresolved external symbol EnvRestoreInstancesFromString
_clips.obj : error LNK2001: unresolved external symbol EnvSlotExistP
_clips.obj : error LNK2001: unresolved external symbol EnvGetNextDefmodule
_clips.obj : error LNK2001: unresolved external symbol EnvSetDefclassWatchInstances
build\lib.win-amd64-3.7\clips\_clips.cp37-win_amd64.pyd : fatal error LNK1120: 208 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120
```

**Comment by noxdafox** [comment]
Hello,

I strongly recommend against trying to compile CLIPS and CLIPSPy yourself as it is a quite tedious procedure. I just uploaded both 32 and 64 bit statically linked version on PyPI.

Therefore, you should be able to install them yourself via: `pip install clipspy`.

In case you want to persevere in your masochistic path here how you can do it (statically linked library).

Retrieve the CLIPS sources from [this link](https://sourceforge.net/projects/clipsrules/files/CLIPS/6.30/clips_core_source_630.zip) and build them with a recent enough version of Visual Studio. Make sure the static object is named `clips.lib`

From CLIPSPy root folder build using this command:

```
python setup.py build_ext --include-dirs=<path-to-static-object-folder> --library-dirs=<path-to-CLIPS-headers>
```

To generate the `wheel` file:
```
python setup.py sdist bdist_wheel
```

You can then install the wheel as usual:
```
pip install <path-to-the-wheel>
```

**Comment by gitttt** [comment]
Okay, the pip installation worked. I did not manage to do the compilation. I have a clips.lib and everything and ran the commands you suggested but I am still getting these unresolved external symbol errors. Do you remember the exact commands you used to compile it using Visual Studio?

**Comment by noxdafox** [comment]
My VisualStudio 2017 license expired (ehm). I will try to provide you the project files I used.

Are you sure you are using the right architecture? Typically you see lots of `error LNK2001` when you try to compile a 64 bits Python library against a 32 bits lib.

**Comment by gitttt** [comment]
Oooooh, yes. My mistake. Setting it up for amd64 worked!
Thanks!

**Comment by gitttt** [comment]
How to build and install clipspy on Windows Server 2016, python 3.7 64 bit, Using Visual Studio 2015 tooling:

1. Download and extract the clips 6.30 sources, link [here],(https://sourceforge.net/projects/clipsrules/files/CLIPS/6.30/clips_core_source_630.zip).
I am extracting it into `c:\tmp\lips_core_source_630`
2. Copy the `makefile.win` file into the `core` directory.
3. Open a terminal and run `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64`
4. `nmake -f makefile.win`
5. `lib.exe /OUT:clips.lib *.obj`
6. `git clone https://github.com/noxdafox/clipspy.git`
7. `cd clipspy`
8. `python setup.py build_ext --include-dirs c:\tmp\clips_core_source_630\core --library-dirs c:\tmp\clips_core_source_630\core`
9. `pip install wheel`
10. `python setup.py sdist bdist_wheel`
11. `pip install .\dist\clipspy-0.2.4_4_g714e8a2-cp37-cp37m-win_amd64.whl`

**Comment by srajan3012** [comment]
can you also please provide steps for installation of clips and clipspy in linux.

**Comment by noxdafox** [comment]
Please do not comment on closed tickets if not strictly related. Open a new ticket explaining the issue including the previous attempts complete with output and the platform you are using (Linux distribution, Python version etc.).
