### ISSUE TITLE
TYPES is missing 'long' type

### ISSUE THREAD

**Issue by slozovsky** [noxdafox/clipspy#20]
Calling a Python function that returns 'long' type fails:

```
From cffi callback <function python_function at 0x7f6e56f65a28>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/clipspy/environment.py", line 227, in python_function
    data.value = ret if ret is not None else clips.common.Symbol('nil')
  File "/usr/lib/python2.7/site-packages/clipspy/data.py", line 71, in value
    dtype = TYPES[type(value)] if self._type is None else self._type
KeyError: (<type 'long'>,)
```

**Comment by noxdafox** [comment]
Hello,

Thanks for reporting this. Can you please provide the code example which reproduces this issue?

**Comment by slozovsky** [comment]
The code is:

```
import clips

def py_func():
    return long(0)

env = clips.Environment()
env.define_function(py_func)

env.eval('(py_func)')
```
It's artificial example. Real application is big. Real function returned result of Redis operation as provided by Python Redis binding.

**Comment by noxdafox** [comment]
I already pushed a fix into the master branch. I was unaware of the `long` type in Python 2. You can pull from master and see if issue #20 and #21 are fixed.

I am not planning to make a release out of such small fixes affecting Python 2. Nevertheless, if a release is really needed please let me know.

**Comment by slozovsky** [comment]
Thank you ver much! No release is needed for me. I'll pull from master.

**Comment by noxdafox** [comment]
I'll close the 2 issues then. Please re-open them if the fixes are not working for you.
