### ISSUE TITLE
Default value is not assigned to a slot

### ISSUE THREAD

**Issue by slozovsky** [noxdafox/clipspy#25]
Consider following example:

```
from clips import Environment

env = Environment()

class_string = """
(defclass MyClass (is-a USER)
  (slot One (type INTEGER)(default 222))
  (slot Two))
"""

env.eval("(watch instances)")
env.eval("(watch slots)")

env.build(class_string)

klass = env.find_class('MyClass')
instance = klass.new_instance('instance-name')
instance['Two'] = 1

print instance
```

Result is:

```
==> instance [instance-name] of MyClass
::= local slot Two in instance instance-name <- 1
[instance-name] of MyClass (One nil) (Two 1)
```

which is wrong. Slot One should be 222 as it is in CLIPS.

```
$ clips
         CLIPS (6.30 3/17/15)
CLIPS> (batch test13.clp)
TRUE
CLIPS> (defclass MyClass (is-a USER)
  (slot One (type INTEGER)(default 222))
  (slot Two))
CLIPS> 
(watch instances)
CLIPS> (watch slots)
CLIPS> 
(make-instance [r1] of MyClass)
==> instance [r1] of MyClass
::= local slot One in instance r1 <- 222
::= local slot Two in instance r1 <- nil
[r1]
CLIPS> 
(exit)
```
Clipspy uses `void *EnvCreateRawInstance(environment,defclassPtr,instanceName);` to create an instance. Documentation for this function states:

> Creates an empty instance with the specified name of the specified
> class. **No slot overrides or class default initializations are performed**
> for the instance.
> 
> **Warning:** This function bypasses message-passing.

`lib/clips.cdef:void *EnvMakeInstance(void *, const char *); ` should be exposed through API;

EnvCreateRawInstance is more of the internal CLIPS function. It's not really needed to be exposed through Clipspy API.

I've added a new method at my environment.py:

```
    def make_instance(self, inststr):
        """Create a new instance from an instance string"""
        ist = lib.EnvMakeInstance(self._env, inststr.encode())
        if ist == ffi.NULL:
            raise CLIPSError(self._env)

        return clips.classes.Instance(self._env, ist)
```

**Comment by noxdafox** [comment]
Unfortunately, in CLIPS 6.30 class and instances C APIs are fairly limited. The programmatic interface does not allow to set default values as well as for generic instance names as per issue #24.

CLIPS 6.40 provides a far better interface for creating and modifying facts/instances. The python bindings for 6.40 are already available (Python 3 only) and you can retrieve them from the [branch 6.40](https://github.com/noxdafox/clipspy/tree/6.40).  

I added the `make_instance` to the `Environment` class. Feel free to open PRs agains `clipspy` in cases like this.

Thanks for reporting this.
