### ISSUE TITLE
printout function using t or stdout in a rule does not make it to stdout in jupyter notebook

### ISSUE THREAD

**Issue by paulbwagner** [noxdafox/clipspy#27]
Everything I have tried in a Jupyter notebook so far is working perfectly _except_ for printing from inside a rule. **env.eval('(printout t "hello")')** works fine but not in the consequent section of a rule, e.g. **'(defrule xyz ... => (printout t "hello") ...)'**.

My workarounds so far have been to write to a file (works fine), asserting printable facts and printing them (not my preference but works), and using embedded python to create a new function to print something (e.g. **def myprint(str): print(str)** and then using define_function() (also works).

Thanks for all the great work on this library, and I hope this turns out to be a simple thing for those CLIPS users with existing rule bases that they want to expose in Jupyter.

**Comment by noxdafox** [comment]
Hello,

could you please clarify which Jupyter notebook are you talking about? Is it [iCLIPS](https://github.com/noxdafox/iclips)? If so, could you please open the issue on its related project?

**Comment by paulbwagner** [comment]
Just a generic jupyter notebook, with “import clips” at the top and other bits in other cells. Again everything seems fine so far but an embedded (printout t …) or (format t …) is not making it to whatever jupyter considers stdout.

I did not know about iCLIPS, that looks interesting too, I will check that out.

Thanks/Regards,

Barney Wagner, GSUSI-PTD/B/T
Subsurface Workflow Consultant – RE
SIP: +1 832 337 0928

**Comment by noxdafox** [comment]
Jupyter kernel captures Python `stdout` and redirects it to the HTML frontend for you. The same does not happen to CLIPS so you need to do it yourself.

CLIPS uses routers (chapter 7 of the [Advanced Programming Guide](http://clipsrules.sourceforge.net/documentation/v630/apg.pdf)) to re-direct the I/O. You can implement a router yourself or use the `LoggingRouter` included in `pyclips`.

```python
import logging
import clips

logging.basicConfig(level=10, format='%(message)s')

env = clips.Environment()

router = clips.LoggingRouter()
router.add_to_environment(env)

env.eval('(printout t "Hello World!" crlf)')
```

If you are already using CLIPS 6.40 (and related `pyclips` bindings).

```python
import logging
import clips

logging.basicConfig(level=10, format='%(message)s')

env = clips.Environment()

router = clips.LoggingRouter()
env.add_router(router)

env.eval('(printout t "Hello World!" crlf)')
```

You can check the `LoggingRouter` [implementation](https://github.com/noxdafox/clipspy/blob/master/clips/router.py#L77) as a reference for implementing your own router.

**Comment by paulbwagner** [comment]
The logging router setup worked, though the output has a reddish background related to being logged (I guess?). I will consult APG for more information. This same reddish background appears with any output, e.g. for your env.eval(‘(printout t …)’) example, but this is not that distracting.

Without using the logging router, the env.eval() example works fine (as before, and no reddish background either); it was when the (printout t …) was [inside a rule] where I had the difficulty (output did not show at all). This distinction of having (printout t …) inside a rule versus outside a rule seems to be important here.

Since I have a couple workarounds I am good with this.

Regards, Barney Wagner

**Comment by noxdafox** [comment]
For the red colour you can see [this](https://stackoverflow.com/questions/25360714/avoid-red-background-color-for-logging-output-in-ipython-notebook) SO question.

It's odd you see the output of `env.eval('(printout t "Hello World!" crlf)')` as it does not happen on my Jupyter Notebook and I don't see how it could work. 

Anyways, I'm glad you got it working.
