### ISSUE TITLE
Failure to install on Windows 10 - 'clips.h' error

### ISSUE THREAD

**Issue by dustintd** [noxdafox/clipspy#28]
I've tried installing on Windows 10 Pro with python 3.7 and I'm getting the following error:

    build\temp.win-amd64-3.7\Release\_clips.c(523): fatal error C1083: Cannot open include file: 'clips.h': No such file or directory

I've tried using both Visual Studio Build Tools for 2015 (v14.00) and 2019, and both give me 'clips.h' error.

Also, the pypi link doesn't seem to show any wheels for windows? (If I'm wrong here let me know)

https://pypi.org/project/clipspy/#modal-close

Any advice or tips on how to solve this? I'd prefer to not install from scratch.

**Comment by noxdafox** [comment]
Hello,

I have not yet build CLIPSPy 0.3.3 for Windows as the last version includes changes related to Linux build only.

You can install the previous version of CLIPSPy which has Windows wheels as well.

```
pip install clipspy==0.3.2
```

**Comment by dustintd** [comment]
Thank you for the quick response! I've got it working with that version.

**Comment by noxdafox** [comment]
As said, the newer version does not bring any change for Windows. I will try to make soon a release to fix this issue but it's not an urgent matter.

**Comment by glacierck** [comment]
@noxdafox  no~~~~ By the way don't forget it
![image](https://user-images.githubusercontent.com/21599896/69709851-2e8caa00-1139-11ea-80ca-8eda64e24ee0.png)

**Comment by DianelRavilla** [comment]
I'm using python 3.8 on Windows 10 and i can't install clipspy. I'm getting the same error as @dustintd but help provided does not help, I've tried to install clipspy 0.3.0, 0.3.1, 0.3.3 (0.3.2 is not available for me) and didn't work:

The full ERROR Message is:

`ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-rzpratj6\\clipspy\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-rzpratj6\\clipspy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-zvvanm4q\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\user\appdata\local\programs\python\python38\Include\clipspy'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-rzpratj6\clipspy\
    Complete output (30 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\clips
    copying clips\agenda.py -> build\lib.win-amd64-3.8\clips
    copying clips\classes.py -> build\lib.win-amd64-3.8\clips
    copying clips\clips_build.py -> build\lib.win-amd64-3.8\clips
    copying clips\common.py -> build\lib.win-amd64-3.8\clips
    copying clips\data.py -> build\lib.win-amd64-3.8\clips
    copying clips\environment.py -> build\lib.win-amd64-3.8\clips
    copying clips\error.py -> build\lib.win-amd64-3.8\clips
    copying clips\facts.py -> build\lib.win-amd64-3.8\clips
    copying clips\functions.py -> build\lib.win-amd64-3.8\clips
    copying clips\modules.py -> build\lib.win-amd64-3.8\clips
    copying clips\router.py -> build\lib.win-amd64-3.8\clips
    copying clips\__init__.py -> build\lib.win-amd64-3.8\clips
    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.8\\Release\\_clips.c'
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    building '_clips' extension
    creating build\temp.win-amd64-3.8\Release\build
    creating build\temp.win-amd64-3.8\Release\build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release\build\temp.win-amd64-3.8\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iclips_source -Ic:\users\user\appdata\local\programs\python\python38\include -Ic:\users\user\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -IC:\SAP\OCS-16_0\include /Tcbuild\temp.win-amd64-3.8\Release\_clips.c /Fobuild\temp.win-amd64-3.8\Release\build\temp.win-amd64-3.8\Release\_clips.obj
    _clips.c
    build\temp.win-amd64-3.8\Release\_clips.c(571): fatal error C1083: No se puede abrir el archivo incluir: 'clips.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\user\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-rzpratj6\\clipspy\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-rzpratj6\\clipspy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-zvvanm4q\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\user\appdata\local\programs\python\python38\Include\clipspy' Check the logs for full command output.
`

**Comment by noxdafox** [comment]
You can find the binaries for Windows [here](https://pypi.org/project/clipspy/0.3.2/#files).

Maximum supported version of Python is 3.7 for both 32 and 64 bit.

New builds will be made available when CLIPS 6.40 will be released.

**Comment by noxdafox** [comment]
Just released builds for Windows supporting Python from 3.6 to 3.8 both 32 and 64 bits.

Closing this issue, please re-open if the problem persists.
