### ISSUE TITLE
Environment load doesn't load text file - complains "not binary file"

### ISSUE THREAD

**Issue by dtdannen** [noxdafox/clipspy#34]
I cannot get a clips environment to load a text file. I'm on windows using clipspy 0.3.2.

Reproducible example:
simple_clips_test.py:

    import clips
    clips_env = clips.Environment()
    demo_clips_facts_filename = "demo.clp"
    clips_env.load(demo_clips_facts_filename)``

demo.clp:

    ;;; Class Structure
    (defclass A  (is-a USER)
       (role concrete)
       (multislot secondary-types)
       (multislot hasIssue (type INSTANCE-NAME)))
    
    (defclass B  (is-a USER)
       (role concrete)
       (multislot secondary-types))
    
    (defclass C  (is-a USER)
       (role concrete)
       (multislot secondary-types))
    
    (defclass D  (is-a USER)
       (role concrete)
       (multislot connectedTo (type INSTANCE-NAME))
       (multislot secondary-types))
    
    ;;; Class Instances
    (definstances individuals
       (temp_a of D)
       (temp_b of D)
    ) ; close up definstance
    
When I use the CLIPS repl to load this, it works just fine:
https://imgur.com/a/VgSdrj1

When debugging, I see that `self._load_text(path)` is called, I'm just not sure what's causing the error.

**Comment by noxdafox** [comment]
Hello,

can you please better describe the issue? Do you get an error message? Could you please paste the traceback?

**Comment by dtdannen** [comment]
Hi yes, this is the error message:

`[BLOAD2] File demo.clp is not a binary construct file.`

**Comment by dtdannen** [comment]
I tried to save the output of the environment after calling the `load()` function and it produced the following file:

    (defclass MAIN::A
       (is-a USER)
       (role concrete)
       (multislot secondary-types)
       (multislot hasIssue
          (type INSTANCE-NAME)))
    
    (defclass MAIN::B
       (is-a USER)
       (role concrete)
       (multislot secondary-types))
    
    (defclass MAIN::C
       (is-a USER)
       (role concrete)
       (multislot secondary-types))
    
    (defclass MAIN::D
       (is-a USER)
       (role concrete)
       (multislot connectedTo
          (type INSTANCE-NAME))
       (multislot secondary-types))
    
    (definstances MAIN::individuals
       (temp_a of D)
       (temp_b of D))


Therefore I think there isn't really an issue - the message about it not being a binary file seems like it can be safely ignored. @noxdafox if you agree I think this issue can be closed

**Comment by noxdafox** [comment]
This is an issue of current `clipspy` version. It combines binary and text file loading into a single `load` API. It first try to load the file as a binary file. If it's unable to do so, it loads it as text file.

This works fine and keeps the API simple. Nevertheless it leads to the above log line to be printed which is definitely misleading.

The new version of `clipspy` based on CLIPS 6.40 provides a `binary` extra argument to better handle loading binary files.

You can safely ignore the above error message.
