### ISSUE TITLE
Cannot add more than one rule

### ISSUE THREAD

**Issue by songlinhou** [noxdafox/clipspy#36]
I have been working on an expert system using clipspy recently. A problem I find is whenever I build a rule, all the previous rules are lost and only one rule can be defined. This is what I have tried.

```python
env.clear()
print("initial rule number:",len(list(env.rules()))) # show how rules when initialized
#initial rule number: 0

env.build(init_rule) # build the 1st rule
print("rule number after 1st build:",len(list(env.rules()))) # show how rules after first build
#rule number after 1st build: 1

env.build(trule) # build the 2nd rule
print("rule number after 2nd build:",len(list(env.rules()))) # show how rules after first build
#rule number after 2nd build: 1
```

If I also tried to merge two rule strs into one, and call env.build() once. It doesn't work.

```python
env.clear()
print("initial rule number:",len(list(env.rules()))) # show how rules when initialized
#initial rule number: 0

two_rules = '\n'.join([init_rule,trule]) # merge two rule strs
env.build(two_rules)
 
print("rule number after build:",len(list(env.rules()))) # show how rules after build
#rule number after build: 1
```

I also tried to put these rules into a text file, and use env.load() function to load that file. However there is still one rule I can find.

I really run out of ways to define more than one rule. I am not sure if this is a bug, or maybe there is something I didn't do correctly. Any help is appreciated!

**Comment by noxdafox** [comment]
Hello,

`clipspy` definitely supports building multiple constructs.

```
In [1]: import clips                                                                                                                                                                                               

In [2]: env = clips.Environment()                                                                                                                                                                                  

In [3]: env.build("(defrule rule-1 =>)")                                                                                                                                                                           

In [4]: env.build("(defrule rule-2 =>)")                                                                                                                                                                           

In [5]: print(list(env.rules()))                                                                                                                                                                                   
[Rule: (defrule MAIN::rule-1
   =>)
, Rule: (defrule MAIN::rule-2
   =>)
]
```

I suspect your rules are somewhat broken and therefore CLIPS does not load them. Could you please provide your rules so I can test them?

**Comment by songlinhou** [comment]
> Hello,
> 
> `clipspy` definitely supports building multiple constructs.
> 
> ```
> In [1]: import clips                                                                                                                                                                                               
> 
> In [2]: env = clips.Environment()                                                                                                                                                                                  
> 
> In [3]: env.build("(defrule rule-1 =>)")                                                                                                                                                                           
> 
> In [4]: env.build("(defrule rule-2 =>)")                                                                                                                                                                           
> 
> In [5]: print(list(env.rules()))                                                                                                                                                                                   
> [Rule: (defrule MAIN::rule-1
>    =>)
> , Rule: (defrule MAIN::rule-2
>    =>)
> ]
> ```
> 
> I suspect your rules are somewhat broken and therefore CLIPS does not load them. Could you please provide your rules so I can test them?

Thank you!

I find the problem is due to the naming of my two rules. I define two rules but they have the same rule name.

Thank you for your help!
