### ISSUE TITLE
ClipsPy empty Error

### ISSUE THREAD

**Issue by 007sya** [noxdafox/clipspy#39]
I am new to CLIPS and to clipsPy. I am trying to create a instance of a CLIPS class

This is the class I have defined and correctly build in my python environment (clipsPy)

```
ENTITIES_CLASS = """
(defclass ENTITY-CLASS (is-a INITIAL-OBJECT)
    (slot text (type STRING))
    (slot confidence (type FLOAT))
    (slot type (type SYMBOL))
)
"""
env.build(ENTITIES_CLASS)
```
This works as expected, but when I try to create an instance of this class:

```
new_instance = "(ent0-0 of ENTITY-CLASS (text 'Bruce Springsteen')(confidence 1.0)(type PER))"
env.make_instance( new_instance )
```
I get this empty error:

https://i.stack.imgur.com/rLTZY.png

I have tried multiple forms of building the new_instance string but none have work :

```
new_instance = '(ent0-0 of ENTITY-CLASS (text "Bruce Springsteen")(confidence 1.0)(type PER))'
new_instance = "(ent0-0 of ENTITY-CLASS (text 'Bruce Springsteen') (confidence 1.0) (type PER) )"
```

Where is my syntax error? I appreciate any help

**Comment by 007sya** [comment]
I restarted Jupyter Notebook and used double quotes for large strings with spaces and it worked:
`new_instance = '(ent0-0 of ENTITY-CLASS (text "Bruce Springsteen")(confidence 1.0)(type PER))'`

**Comment by noxdafox** [comment]
Issue discussed in this [StackOverflow](https://stackoverflow.com/questions/64605683/clips-empty-error-in-clipspy-when-using-make-instance) question.
