### ISSUE TITLE
How to query Fact by index

### ISSUE THREAD

**Issue by glacierck** [noxdafox/clipspy#40]
I can find the rules by 'find_rule',but why not provide the 'find_fact' method ?
I need help.

**Comment by glacierck** [comment]
I find a method that can be used to solve this problem. check fact info by index and slot-name.
‘’‘
Environment.eval('(fact-slot-value <index> <slot>)')

‘’’

**Comment by noxdafox** [comment]
You can search for rules, classes and deftemplates as they are unique constructs. Therefore, their name can be used to uniquely identify them.

Facts are nameless instances of deftemplates and cannot be easily referred to.

If you want to find a fact given its index you can always do the following:
```python
f3 = list(env.facts())[3]
```
