### ISSUE TITLE
[BLOAD2] 

### ISSUE THREAD

**Issue by coding-fantastic** [noxdafox/clipspy#42]
The error => [BLOAD2] File book.clp is not a binary construct file.

*******************************
## The code.
from clips import Environment, Symbol

env = Environment()

env.clear()

env.load('book.clp')

env.facts()

env.run()

*******************************

*******************************
## book.clp file
(deftemplate book
    (multislot surname)(slot name)(multislot title) 
)

(deffacts initial
(book (surname J.P.)(name Dubreuil)(title History of francmasons))
(book (surname T.)(name Eker)(title Secrets of millionaire mind)))

(defrule find_title
    ?book<-(book(name Eker))
    =>
    (printout t ?book crlf)
)
*******************************

**Comment by noxdafox** [comment]
Do you actually get an exception or is it just a log line? 

The engine tries first to load it as binary file and then as text file. In certain environment, a spurious message `[BLOAD2] File book.clp is not a binary construct file.` might show up. Nevertheless, the constructs were actually loaded correctly.

**Comment by noxdafox** [comment]
`clipspy` `1.0.0` supports an improved `load` logic which allows to choose whether a file is in binary format or not rather than trying to guess it.
