### ISSUE TITLE
Has anyone tried to make a web frontend?

### ISSUE THREAD

**Issue by dogweather** [noxdafox/clipspy#51]
I'm brainstorming about running clipspy in Flask with a stateless endpoint. E.g., the web client's asserted facts would be re-sent with every GET request. The endpoint would create a new environment for the request, and terminate it when done. The reason would be to scale well for the web.

Being able to make CLIPS web apps would be pretty powerful.

**Comment by noxdafox** [comment]
GitHub issues are for bug reports and feature requests not for questions and guidance.

For those, there is the related [stackoverflow](https://stackoverflow.com/questions/tagged/clipspy) tag and the CLIPS [mailing list](https://groups.google.com/g/clipsesg).

A quick search through the [projects](https://github.com/noxdafox/clipspy/network/dependents) using `pyclips` would have provided few examples of what you are talking about:
- https://github.com/lutfiandri/diseases-diagnosis
- https://github.com/IRS-PM/IRS-PM-2020-01-18-IS02PT-GRP15-IntelligentClaimsSystem
- https://github.com/masterraf21/lending-expert-system
