### ISSUE TITLE
Question: pretty print or formatter available?

### ISSUE THREAD

**Issue by juanjawbone** [noxdafox/clipspy#53]
From `pyclips` it looks like a pretty printer might be available via the underlying C API, see [example 1](https://github.com/almostearthling/pyclips/blob/e8d2b75e0ca328b6320637520e3dd6491ca15466/clips/_clips_wrap.py#L1300) or [example 2](https://github.com/almostearthling/pyclips/blob/e8d2b75e0ca328b6320637520e3dd6491ca15466/clips/_clips_wrap.py#L1157).

I'm currently exploring this codebase to see if something similar is available, either an API to pretty printing, or access to the underlying C library (perhaps `clips._clips.ffi`?).

If anyone knows, please let me know. I'll answer my own question if I find an answer. Thanks!

Use case:

I'm basically trying to turn an ugly single-line blob of Lisp-like code into something which is indented nicely.

**Comment by opyate** [comment]
As I just needed a pretty printer, I whipped this up:
```
def clips_pprint(clips_str: str) -> str:
    """Pretty-prints a CLIPS string.

    Indents a CLIPS string for easier visual confirmation during development
    and verification.
    Assumes the CLIPS string is valid CLIPS, i.e. braces are paired.
    """
    LB = "("
    RB = ")"
    TAB = "    "
    formatted_clips_str = ""
    tab_count = 0
    for c in clips_str:
        if c == LB:
            formatted_clips_str += os.linesep
            for _i in range(tab_count):
                formatted_clips_str += TAB

            tab_count += 1
        elif c == RB:
            tab_count -= 1
        formatted_clips_str += c

    return formatted_clips_str.strip()
```

**Comment by noxdafox** [comment]
Hello,

GitHub is for reporting issues or requesting features and not for guidance, for that, you can use the dedicated [SO tag](https://stackoverflow.com/questions/tagged/clipspy) or the [mailing list](https://groups.google.com/g/clipsesg).

Each construct in CLIPSPy can be pretty printed via it's `__str__` protocol.

```python
In [1]: import clips

In [2]: env = clips.Environment()

In [3]: fact = env.assert_string('(foo bar baz)')

In [4]: print(fact)
(foo bar baz)

In [5]: str(fact)
Out[5]: '(foo bar baz)'

In [6]: env.build("""
   ...: (defrule test
   ...:   (foo bar baz)
   ...:   =>
   ...:   (println "test"))
   ...: """)

In [7]: rule = env.find_rule('test')

In [8]: print(rule)
(defrule MAIN::test (foo bar baz) => (println "test"))
```
