### ISSUE TITLE
Installation problem with Python 3.10

### ISSUE THREAD

**Issue by InterestedInProgramming** [noxdafox/clipspy#54]
Hello, 

I would like to install clipspy via pip. 
Unfortunately it does not work for me with Python 3.10. 
With 3.9 it works. 

Thanks in advance. 

Many greetings! 

My installed packages for 3.10. are:
cffi       1.15.1
pip        22.1.2
pycparser  2.21
setuptools 63.2.0
wheel      0.37.1
where setuptools was upgraded with pip before trying to install clipspy. 

This is what the console says (VS code with Git Bash):

Collecting clipspy
  Using cached clipspy-1.0.0.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cffi>=1.0.0 in c:\users\...\desktop\test\testing310\lib\site-packages (from clipspy) (1.15.1)
Requirement already satisfied: pycparser in c:\users\...\desktop\test\testing310\lib\site-packages (from cffi>=1.0.0->clipspy) (2.21)
Building wheels for collected packages: clipspy
  Building wheel for clipspy (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\clips
      copying clips\agenda.py -> build\lib.win-amd64-cpython-310\clips     
      copying clips\classes.py -> build\lib.win-amd64-cpython-310\clips    
      copying clips\clips_build.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\common.py -> build\lib.win-amd64-cpython-310\clips     
      copying clips\environment.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\facts.py -> build\lib.win-amd64-cpython-310\clips      
      copying clips\functions.py -> build\lib.win-amd64-cpython-310\clips  
      copying clips\modules.py -> build\lib.win-amd64-cpython-310\clips    
      copying clips\routers.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\values.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\__init__.py -> build\lib.win-amd64-cpython-310\clips
      running build_ext
      generating cffi module 'build\\temp.win-amd64-cpython-310\\Release\\_clips.c'    
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      building '_clips' extension
      creating build\temp.win-amd64-cpython-310\Release\build
      creating build\temp.win-amd64-cpython-310\Release\build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release\build\temp.win-amd64-cpython-310\Release
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iclips_source -IC:\Users\...\Desktop\test\testing310\include -IC:\Users\...\AppData\Local\Programs\Python\Python310\include -IC:\Users\...\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcbuild\temp.win-amd64-cpython-310\Release\_clips.c /Fobuild\temp.win-amd64-cpython-310\Release\build\temp.win-amd64-cpython-310\Release\_clips.obj        
      _clips.c
      build\temp.win-amd64-cpython-310\Release\_clips.c(570): fatal error C1083: Datei 
(Include) kann nicht ge”ffnet werden: "clips.h": No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2    
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip. 
  ERROR: Failed building wheel for clipspy
  Running setup.py clean for clipspy
Failed to build clipspy
Installing collected packages: clipspy
  Running setup.py install for clipspy ... error
  error: subprocess-exited-with-error

  × Running setup.py install for clipspy did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running install
      C:\Users\...\Desktop\test\testing310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\clips
      copying clips\agenda.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\classes.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\clips_build.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\common.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\environment.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\facts.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\functions.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\modules.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\routers.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\values.py -> build\lib.win-amd64-cpython-310\clips
      copying clips\__init__.py -> build\lib.win-amd64-cpython-310\clips
      running build_ext
      generating cffi module 'build\\temp.win-amd64-cpython-310\\Release\\_clips.c'
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      building '_clips' extension
      creating build\temp.win-amd64-cpython-310\Release\build
      creating build\temp.win-amd64-cpython-310\Release\build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release\build\temp.win-amd64-cpython-310\Release
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iclips_source -IC:\Users\...\Desktop\test\testing310\include -IC:\Users\...\AppData\Local\Programs\Python\Python310\include -IC:\Users\...\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcbuild\temp.win-amd64-cpython-310\Release\_clips.c /Fobuild\temp.win-amd64-cpython-310\Release\build\temp.win-amd64-cpython-310\Release\_clips.obj
      _clips.c
      build\temp.win-amd64-cpython-310\Release\_clips.c(570): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "clips.h": No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> clipspy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by chrstsrs** [comment]
I had a similar problem, as trying to install pyclips on docker, based on an alpine image. Finally I changed the base image to python:3.10.7-bullseye and worked.

**Comment by noxdafox** [comment]
New binaries for more recent versions of Windows and Linux have been uploaded to PyPi.
