### ISSUE TITLE
Unable to install clipspy in mac bookpro

### ISSUE THREAD

**Issue by ramakrse** [noxdafox/clipspy#57]
I get the below error (partial - last elements) while installing using pip install clipspy.
build/temp.macosx-10.9-x86_64-cpython-312/_clips.c:570:10: fatal error: 'clips.h' file not found
#include <clips.h>
^~~~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for clipspy
Running setup.py clean for clipspy
Failed to build clipspy
ERROR: Could not build wheels for clipspy, which is required to install pyproject.toml-based project

**Comment by noxdafox** [comment]
Hello, what MAC architecture are you using? Is it a M1/M2...?

**Comment by ramakrse** [comment]
@noxdafox - Processor is 2.3 GHz 8-Core Intel Core i9..

**Comment by noxdafox** [comment]
Now I see, you are using Python 3.12 and there is not a build for that version on MAC yet. I will fix it ASAP.

**Comment by noxdafox** [comment]
New builds for 3.12 for Mac and Wndows have been uploaded on PyPi.
