### ISSUE TITLE
Mac M architecture

### ISSUE THREAD

**Issue by tobrien6** [noxdafox/clipspy#58]
Are there any plans to get this working for M architectures? The CLIPS engine downloaded from the official website seems to work fine on my M2.

**Comment by noxdafox** [comment]
Hello,

Yes, once GitHub actions support this architecture for its build.

https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587

**Comment by tobrien6** [comment]
I built it with Make, but getting this error now:

ModuleNotFoundError: No module named 'clips._clips'

**Comment by kgantchev** [comment]
> Yes, once GitHub actions support this architecture for its build.

Might I make a suggestion? Feel free to use [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's **AND** we have a free tier for OSS projects (see below).

## Install Instructrions 

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Or try the M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label | Price on FlyCI | Price on GitHub |
|-----------|-------|-----------|----------|-------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB | flyci-macos-large-latest-m1   | $0.06          | -             |
| M1        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m1  | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB | flyci-macos-large-latest-m2   | $0.08          | -             |
| M2        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m2  | $0.16          | -             |

## 500 mins/month Free for Public Repos

If your repo is public, then FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner.  

Best Regards,
Kiril Gantchev
CEO and co-founder of [FlyCI](https://flyci.net)

**Comment by noxdafox** [comment]
Version `1.0.3` now supports Apple Silicon.
