### ISSUE TITLE
How to do something like (watch activations) when loading rules from file?

### ISSUE THREAD

**Issue by ForceConstant** [noxdafox/clipspy#64]
I see how you can add a watch for a construct created using the python library, but can't see how to do something like just globally set "(watch activations)" or rules, etc.

**Comment by noxdafox** [comment]
Hello,

I am not sure I understand the question.

You can indeed watch the activation via:
```python
environment = clips.Environment()

environment.watch_activations = True
```

https://clipspy.readthedocs.io/en/latest/clips.html#clips.agenda.Rule.watch_activations
