### ISSUE TITLE
Defining a python function in clips with a different name

### ISSUE THREAD

**Issue by gitttt** [noxdafox/clipspy#7]
In pyclips, one could do this:
`clips.RegisterPythonFunction(function_to_register, function_name_in_clips)`

In clipspy, I can only do this:
`clips_env.define_function(function_to_register)`

Is this by design? I tried to set the `__name__` property of `function_to_register` but it didn't work. Is it possible to change the name?

**Comment by noxdafox** [comment]
Right now, `clipspy` will use the same name of the Python function.

```
env.define_function(my_python_function)

env.eval('(my_python_function "a_string" a_symbol 0 1.0)')
```

Do you have a valid use case for renaming the function in CLIPS?

**Comment by gitttt** [comment]
Yes, I do. I am calling a "logger" function in my rules. But this logger function varies, e.g. "csv_logger", "print_logger", ...

**Comment by noxdafox** [comment]
Feature added in `clipspy` 0.3.0.

I will upload on `pypi` Windows builds later in the week-end.

Please re-open the issue if you feel it was not handled satisfactorily.
