### ISSUE TITLE
Getting instance slots as dictionary

### ISSUE THREAD

**Issue by gitttt** [noxdafox/clipspy#8]
Same thing as [this SO post](https://stackoverflow.com/q/52836753/4480139).

Is there a built-in way to get all slots and their values from an instance as a dictionary?

I created this helper function but maybe there is a better way (using the `Instance` class in `classes.py`)?

Don't worry if there isn't, just checking because I used the `Slots()` method in `pyclips` a lot.

**Comment by noxdafox** [comment]
There is no such API at the moment. What can be done is an interface similar to `TemplateFacts`:

```
dict(instance) # returns a dictionary containing the mapping slot => value
```

**Comment by noxdafox** [comment]
The last patch series unifies the access to the objects data.

ImpliedFacts data will be accessible as for lists.
TemplateFacts and Instances data will be accessible as for dictionaries.

All the above classes implement the `__getitem__` and the `__iter__` protocols.

**Comment by noxdafox** [comment]
Feature added in `clipspy` 0.3.0.

I will upload on `pypi` Windows builds later in the week-end.

Please re-open the issue if you feel it was not handled satisfactorily. 

Example:

```python
klass = self.env.find_class('CLASS')
instance = klass.new_instance('test-instance')
instance['Slot'] = Symbol('value')

dict(instance)
```
